### ISSUE TITLE
cleanCSS version 4 doesn't work

### ISSUE THREAD

**Issue by esjewett** [humanitiesplusdesign/fibra#180]
gulp-clean-css 2.2.2 (currently using) pulls in cleanCSS version 3
gulp-clean-css 4.0.3(?) pulls in clean CSS version 4.

The later explodes when it tries to process main.styl/main.css. Seems like it may be something to do with the imports.

**Comment by jiemakel** [comment]
The error is:
```
Error: Uncaught, unspecified "error" event. (Ignoring local @import of "../components/construct-view/construct.css" as resource is missing.)
...
    at /Users/jiemakel/tyo/fibra/node_modules/gulp-clean-css/index.js:32:16
    at /Users/jiemakel/tyo/fibra/node_modules/clean-css/lib/clean.js:107:9
    at Object.callback (/Users/jiemakel/tyo/fibra/node_modules/clean-css/lib/reader/read-sources.js:29:9)
    at doApplySourceMaps (/Users/jiemakel/tyo/fibra/node_modules/clean-css/lib/reader/apply-source-maps.js:61:23)
...
```

**Comment by jiemakel** [comment]
https://github.com/scniro/gulp-clean-css/issues/31
